openapi: 3.0.0
info:
  title: Ads API
  version: 1.0.0
paths:
  /ads:
    get:
      summary: Get all ads
      operationId: getAds
      responses:
        '200':
          description: A list of ads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ad'
    post:
      summary: Create a new ad
      operationId: createAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ad'
      responses:
        '201':
          description: The created ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
  /ads/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an ad by ID
      operationId: getAdById
      responses:
        '200':
          description: The ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
    put:
      summary: Update an ad by ID
      operationId: updateAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ad'
      responses:
        '200':
          description: The updated ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
    delete:
      summary: Delete an ad by ID
      operationId: deleteAd
      responses:
        '204':
          description: Successfully deleted
components:
  schemas:
    Ad:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Unique identifier for the ad
        title:
          type: string
          description: Title of the ad
        description:
          type: string
          description: Description of the ad
        price:
          type: number
          format: float
          description: Price of the ad
        image:
          type: string
          description: Image URL of the ad
        created_at:
          type: string
          format: date-time
          description: The date and time when the ad was created
        user_id:
          type: integer
          format: int32
          description: Unique identifier for the user who posted the ad
      required:
        - id
        - title